name: Deploy Flutter Web to Firebase Hosting (subfolder)

on:
  push:
    branches:
      - main  # change this if you're using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Install dependencies
        run: flutter pub get
        working-directory: finalend

      - name: Build Flutter Web
        run: flutter build web
        working-directory: finalend

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIXIT_2A354 }}"
          channelId: live
          projectId: fixit-2a354
          entryPoint: finalend
